--- 
Servicephpmyadmin: 
  container_name: phpmyadmin
  environment: 
    MYSQL_PASSWORD: qwerty1234
    MYSQL_ROOT_PASSWORD: qwerty1234
    MYSQL_USER: amrilsyaifa
    UPLOAD_LIMIT: 3000000000
  image: phpmyadmin/phpmyadmin
  links: 
    - "db:db"
  networks: 
    - app-network
  ports: 
    - "7000:80"
app: 
  build: ~
  container_name: app
  context: "."
  dockerfile: Dockerfile
  environment: 
    SERVICE_NAME: app
    SERVICE_TAGS: dev
  image: php_service
  networks: 
    - app-network
  restart: unless-stopped
  tty: true
  volumes: 
    - "./:/var/www"
    - "./php/local.ini:/usr/local/etc/php/conf.d/local.ini"
  working_dir: /var/www
app-network: ~
db: 
  container_name: db
  environment: 
    MYSQL_DATABASE: laravel
    MYSQL_PASSWORD: qwerty1234
    MYSQL_ROOT_PASSWORD: qwerty1234
    MYSQL_USER: amrilsyaifa
    SERVICE_NAME: mysql
    SERVICE_TAGS: dev
  image: mysql
  networks: 
    - app-network
  ports: 
    - "33061:3306"
  restart: unless-stopped
  tty: true
driver: local
lbdata: ~
networks: ~
services: ~
version: "3"
volumes: ~
webserver: 
  container_name: webserver
  image: "nginx:alpine"
  networks: 
    - app-network
  ports: 
    - "88:80"
    - "443:443"
  restart: unless-stopped
  tty: true
  volumes: 
    - "./:/var/www"
    - "./nginx/conf.d/:/etc/nginx/conf.d/"
